parameters:
#    kebab_user.example.class: Kebab\UserBundle\Example

services:
#    kebab_user.example:
#        class: %kebab_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
