<?php

namespace Kebab\CaisseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PerissableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerissableRepository extends EntityRepository
{
}
