<?php

namespace Kebab\CaisseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VenteRepository extends EntityRepository
{
    public function findVenteByMonthYear($year, $month){
        $query = $this->_em->createQuery('SELECT v FROM KebabCaisseBundle:Vente v WHERE YEAR(v.date)=:year AND MONTH(v.date)=:month ORDER BY v.date');
        $query->setParameter('year', $year);
        $query->setParameter('month', $month);
//        $query->orderBy('v.date', 'DESC');
        return $query->getResult();        
    }
}
