<?php

namespace Kebab\CaisseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VersementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VersementRepository extends EntityRepository
{
}
