<?php

namespace Kebab\ComptaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SalaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalaireRepository extends EntityRepository
{
    public function findSalairesByMonthYear($year, $month) {
        
        $query = $this->_em->createQuery('SELECT s FROM KebabComptaBundle:Salaire s WHERE YEAR(s.date)=:year AND MONTH(s.date)=:month');
        $query->setParameter('year', $year);
        $query->setParameter('month', $month);
        return $query->getResult();
    }
}
